//! This is an implementation of UUIDs specified by the RFC 9562 (https://www.rfc-editor.org/rfc/rfc9562)
//! This package was created as an exercise to learn Zig. The Go and Elixir implementations were used as inspiration.
//! In addition, there are other Zig implementations that cover the same range of functionality.
//!
const std = @import("std");
const Sha1 = std.crypto.hash.Sha1;
const Md5 = std.crypto.hash.Md5;
const random = std.crypto.random;

// Indices in the UUID string representation for each byte.
const default_encoded_pos = [16]u8{0, 2, 4, 6, 9, 11, 14, 16, 19, 21, 24, 26, 28, 30, 32, 34};
const hex_encoded_pos = [16]u8{0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30};

// Used to format hex values
const hex = "0123456789ABCDEF";

// UUID layouts and versions
const uuid_v1 = 0x10;
const uuid_v3 = 0x30;
const uuid_v4 = 0x40;
const uuid_v5 = 0x50;

/// see https://www.rfc-editor.org/rfc/rfc9562#name-namespace-id-usage-and-allo
pub const Namespace = enum {
    dns,
    nil,
    oid,
    url,
    x500,
};

/// Specifies the format when calling format function
pub const Format = enum {
    /// The default format, for example: "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
    default,
    /// The hex format, for example: "6ba7b8109dad11d180b400c04fd430c8"
    hex,
    /// The slug format generated by `url_safe_no_pad`, for example: "wjKrAJQUEeyzyJ9r3s7YRg"
    slug,
};

// The predefined namespace ids:
const nil_prefix = [16]u8{0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};
const dns_prefix = [16]u8{0x6b, 0xa7, 0xb8, 0x10, 0x9d, 0xad, 0x11, 0xd1, 0x80, 0xb4, 0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8};
const url_prefix = [16]u8{0x6b, 0xa7, 0xb8, 0x11, 0x9d, 0xad, 0x11, 0xd1, 0x80, 0xb4, 0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8};
const oid_prefix = [16]u8{0x6b, 0xa7, 0xb8, 0x12, 0x9d, 0xad, 0x11, 0xd1, 0x80, 0xb4, 0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8};
const x500_prefix = [16]u8{0x6b, 0xa7, 0xb8, 0x14, 0x9d, 0xad, 0x11, 0xd1, 0x80, 0xb4, 0x00, 0xc0, 0x4f, 0xd4, 0x30, 0xc8};

// Used to calculate the timestamp for UUIDv1 and UUIDv6
const lillian : i64 = 2_299_160;       // Julian day of 15 Oct 1582
const unix : i64= 2_440_587;           // Julian day of 1 Jan 1970
const epoch = unix - lillian;          // Days between epochs
const g1582 = epoch * 86_400;          // seconds between epochs
const g1582ns100 = g1582 * 10_000_000; // 100s of a nanoseconds between epochs

const UUID = @This();

/// Contains the UUID as a array of 16 bytes.
raw : [16]u8,

/// Creates a UUID using the raw bytes in `uuid` without any validations.
pub fn init(uuid: [16]u8) UUID {
    return UUID{
        .raw = uuid
    };
}

/// Creates a UUID using the raw u128 without any validations.
pub fn initWithInt(uuid: u128) UUID {
    var buf: [16]u8 = undefined;
    std.mem.writeInt(u128, &buf, uuid, .big);

    return UUID{
        .raw = buf
    };
}

/// Converts the UUID to the UUID string representation.
pub fn format(self: UUID, comptime f: []const u8, options: std.fmt.FormatOptions, writer: anytype) !void {
    _ = options;
    _ = f;

    return writer.print("{}-{}-{}-{}-{}", .{
        std.fmt.fmtSliceHexUpper(self.bytes[0..4]),
        std.fmt.fmtSliceHexUpper(self.bytes[4..6]),
        std.fmt.fmtSliceHexUpper(self.bytes[6..8]),
        std.fmt.fmtSliceHexUpper(self.bytes[8..10]),
        std.fmt.fmtSliceHexUpper(self.bytes[10..16]),
    });
}


/// Creates a UUIDv1 using the provided node identifier (typically a 48-bit IEEE 802 MAC address).
///
/// The `nodeId` slice must contain 6 bytes. If you do not have a hardware MAC address,
/// you may call `randomNodeId` once and reuse the value for subsequent calls.
///
/// The clock sequence starts at 1 by default and is incremented automatically for each call.
pub fn uuid1WithNodeId(nodeId: []const u8) UUID {

    var result: UUID = undefined;
    const timestamp : u60 = @intCast(@divTrunc(std.time.nanoTimestamp(), 100) + g1582ns100);
    const seq = incSeq();
    result.raw[0] = @truncate(timestamp >> 24);
    result.raw[1] = @truncate(timestamp >> 16);
    result.raw[2] = @truncate(timestamp >> 8);
    result.raw[3] = @truncate(timestamp);
    result.raw[4] = @truncate(timestamp >> 40);
    result.raw[5] = @truncate(timestamp >> 32);
    result.raw[6] = @as(u8, @truncate(timestamp >> 56)) | 0x10; // version
    result.raw[7] = @truncate(timestamp >> 48);
    result.raw[8] = 0x80 | @as(u8, @truncate(seq >> 6)); // variant + seq
    result.raw[9] = @truncate(seq);
    @memcpy(result.raw[10..], nodeId);

    return result;
}

/// Creates a UUIDv1 value. The node id is generated for each call.
/// The clock sequence starts at 1 by default and is incremented automatically for each call.
pub fn uuid1() UUID {

    var result: UUID = undefined;
    const timestamp: u60 = @intCast(@divTrunc(std.time.nanoTimestamp(), 100) + g1582ns100);
    const seq = incSeq();
    result.raw[0] = @truncate(timestamp >> 24);
    result.raw[1] = @truncate(timestamp >> 16);
    result.raw[2] = @truncate(timestamp >> 8);
    result.raw[3] = @truncate(timestamp);
    result.raw[4] = @truncate(timestamp >> 40);
    result.raw[5] = @truncate(timestamp >> 32);
    result.raw[6] = @as(u8, @truncate(timestamp >> 56)) | 0x10; // version
    result.raw[7] = @truncate(timestamp >> 48);
    result.raw[8] = 0x80 | @as(u8, @truncate(seq >> 6)); // variant + seq
    result.raw[9] = @truncate(seq);

    // After generating the 48-bit fully randomized node value, implementations MUST set the least significant bit of the first octet of the Node ID to 1
    random.bytes(result.raw[10..]);
    result.raw[0] = result.raw[0] | 0x01;

    return result;
}

/// Generates a new UUID v3 where the namespace is a string or
/// another UUID. It uses the MD5 hash to generate the UUID.
pub fn uuid3(name: []const u8, namespace: []const u8) UUID {
    return namebasedMd5UUID(namespace, name);
}

/// Generate a new UUID v3 where the namespace is a predefined namespace.
/// It uses the MD5 hash to generate the UUID.
pub fn uuid3WithNamespace(name: []const u8, namespace: Namespace) UUID {
    switch(namespace) {
        .dns => return namebasedMd5UUID(&dns_prefix, name),
        .url => return namebasedMd5UUID(&url_prefix, name),
        .oid => return namebasedMd5UUID(&oid_prefix, name),
        .x500 => return namebasedMd5UUID(&x500_prefix, name),
        .nil => return namebasedMd5UUID(&nil_prefix, name),
    }
}

/// Generate a new UUID v4. This version uses pseudo-random bytes generated by
/// the `crypto` package.
pub fn uuid4() UUID {
    var random_bytes: [16]u8 = undefined;
    random.bytes(&random_bytes);
    composeNamebasedUuid(uuid_v4, &random_bytes);
    return UUID {
        .raw = random_bytes,
    };
}

/// Generate a new UUID v5. It uses the SHA1-Hash a used defined string namespace
/// to produce the UUID.
pub fn uuid5(name: []const u8, namespace: []const u8) UUID {
    return namebasedSha1UUID(namespace, name);
}

/// Generate a new UUID v5. It uses the SHA1-Hash and a predefined namespace
/// to produce the UUID.
pub fn uuid5WithNamespace(name: []const u8, namespace: Namespace) UUID {
    switch(namespace) {
        .dns => return namebasedSha1UUID(&dns_prefix, name),
        .url => return namebasedSha1UUID(&url_prefix, name),
        .oid => return namebasedSha1UUID(&oid_prefix, name),
        .x500 => return namebasedSha1UUID(&x500_prefix, name),
        .nil => return namebasedSha1UUID(&nil_prefix, name),
    }
}

/// Creates a random generated node id. Can be used, if the MAC address is not available.
pub fn randomNodeId(out: []u8) void {
    random.bytes(out[0..]);
    out[0] = out[0] | 0x01;
}

/// Returns the UUID as an unsigned 128-bit integer.
pub fn toInt(self: *const UUID) u128 {
    return std.mem.readInt(u128, self.raw[0..], .big);
}

/// Returns the UUID version number.
pub fn version(self: *const UUID) u4 {
    return @truncate(self.raw[6] >> 4);
}

/// Formats the UUID using different formats
pub fn formatUUID(self: *const UUID, f: Format, out: []u8) []const u8  {
    switch(f) {
        .default => return formatDefault(self, out),
        .hex => return formatHex(self, out),
        .slug => return formatSlug(self, out),
    }
}

fn namebasedMd5UUID(prefix: []const u8, data: []const u8) UUID {
    var hasher = Md5.init(.{});
    hasher.update(prefix);
    hasher.update(data);
    var hash_buffer: [16]u8 = undefined;
    hasher.final(&hash_buffer);
    composeNamebasedUuid(uuid_v3, &hash_buffer);

    return UUID {
        .raw = hash_buffer,
    };
}

fn namebasedSha1UUID(prefix: []const u8, data: []const u8) UUID {
    var hasher = Sha1.init(.{});
    hasher.update(prefix);
    hasher.update(data);
    var hash_buffer: [20]u8 = undefined;
    hasher.final(&hash_buffer);
    composeNamebasedUuid(uuid_v5, hash_buffer[0..16]);

    return UUID {
        .raw = hash_buffer[0..16].*,
    };
}

fn composeNamebasedUuid(vsn: u8, buf: []u8) void {
    // version
    buf[6] = (buf[6] & 0x0f) | vsn;
    // Variant 1
    buf[8] = (buf[8] & 0x3f) | 0x80;
}

// Default formating, "6ba7b810-9dad-11d1-80b4-00c04fd430c8"
fn formatDefault(self: *const UUID, out: []u8) []const u8 {
    out[8] = '-';
    out[13] = '-';
    out[18] = '-';
    out[23] = '-';
    inline for (default_encoded_pos, 0..) |i, j| {
        out[i + 0] = hex[self.raw[j] >> 4];
        out[i + 1] = hex[self.raw[j] & 0x0f];
    }

    return out[0..36];
}

// Hex formating, "6ba7b8109dad11d180b400c04fd430c8"
fn formatHex(self: *const UUID, out: []u8) []const u8  {
    inline for (hex_encoded_pos, 0..) |i, j| {
        out[i + 0] = hex[self.raw[j] >> 4];
        out[i + 1] = hex[self.raw[j] & 0x0f];
    }

    return out[0..32];
}

// Slug formating, "wjKrAJQUEeyzyJ9r3s7YRg"
fn formatSlug(self: *const UUID, out: []u8) []const u8  {
    return std.base64.url_safe_no_pad.Encoder.encode(out, &self.raw);
}

// Increase the sequence, used by UUIDv1 and UUIDv6
fn incSeq() u14 {
    const Sequence = struct {
        var value : u14 = 0;
    };

    while(true) {
        const next_seq, const overflow = @addWithOverflow(Sequence.value, 1);
        _ = overflow;
        if(@cmpxchgStrong(u14, &Sequence.value, Sequence.value, next_seq, .monotonic, .monotonic) == null) {
            return next_seq;
        }
    }
}

test "should init with u128 values" {
    const uuid = UUID.initWithInt(@as(u128, 0x00AABBCCDDEE));
    var buf36: [36]u8 = undefined;
    const out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "00000000-0000-0000-0000-00AABBCCDDEE");

    const uuid_1 = UUID.uuid1();
    const value_1 = uuid_1.toInt();
    const uuid_2 = UUID.initWithInt(value_1);
    const value_2 = uuid_2.toInt();

    try std.testing.expect(value_1 == value_2);
}

test "should return the correct version" {
    const uuid = UUID.uuid1();
    try std.testing.expect(uuid.version() == 1);
}

test "should use the specified node id" {
    const nodeId = [6]u8{0x00, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE};
    var uuid = UUID.uuid1WithNodeId(&nodeId);

    try std.testing.expect(uuid.version() == 1);
    var buf36: [36]u8 = undefined;
    var out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out[24..], "00AABBCCDDEE");

    uuid = UUID.uuid1WithNodeId(&nodeId);

    out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out[24..], "00AABBCCDDEE");
}

test "should format a UUIDv1 value" {

    var buf36: [36]u8 = undefined;
    const uuid = UUID.init(.{0xC2, 0x32, 0xAB, 0x00, 0x94, 0x14, 0x11, 0xEC, 0xB3, 0xC8, 0x9F, 0x6B, 0xDE, 0xCE, 0xD8, 0x46});
    var out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "C232AB00-9414-11EC-B3C8-9F6BDECED846");

    out = uuid.formatUUID(.hex, &buf36);
    try std.testing.expectEqualStrings(out, "C232AB00941411ECB3C89F6BDECED846");

    out = uuid.formatUUID(.slug, &buf36);
    try std.testing.expectEqualStrings(out, "wjKrAJQUEeyzyJ9r3s7YRg");

    try std.testing.expect(uuid.version() == 1);
}


test "format should return default, hex and slug strings" {
    var buf36: [36]u8 = undefined;
    const uuid = UUID.init(.{0} ** 16);

    var out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "00000000-0000-0000-0000-000000000000");

    out = uuid.formatUUID(.hex, &buf36);
    try std.testing.expectEqualStrings(out, "00000000000000000000000000000000");

    out = uuid.formatUUID(.slug, &buf36);
    try std.testing.expectEqualStrings(out, "AAAAAAAAAAAAAAAAAAAAAA");
}


test "seqInc should increment the seq after calling" {
    const start = incSeq();
    try std.testing.expect(incSeq() == start + 1);
    try std.testing.expect(incSeq() == start + 2);
    try std.testing.expect(incSeq() == start + 3);
    try std.testing.expect(incSeq() == start + 4);
}

test "generates a new UUID5 based on a UUID" {
    const uuid = UUID.uuid5("this is my string", "222BA182-5BDF-404F-8D02-BC0C18C80195");
    var buf36: [36]u8 = undefined;
    const out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "CB3C6E3C-85FE-5023-9830-F807DA0AF3F2");
}

test "generates new UUID3s based on different pre defined namespace" {
    var buf36: [36]u8 = undefined;
    var uuid = UUID.uuid3WithNamespace("this is my string", .dns);
    var out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "467B3FDF-E05D-3632-9B4A-519AE4921D61");

    uuid = UUID.uuid3WithNamespace("this is my string", .url);
    out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "ABF9BA64-EE10-3899-AEED-154AA4B64831");

    uuid = UUID.uuid3WithNamespace("this is my string", .oid);
    out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "8EF1F24D-9A59-31B2-9558-05CDF10DE75E");

    uuid = UUID.uuid3WithNamespace("this is my string", .x500);
    out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "A4F71444-6F2A-3DDA-87D4-EED37F763531");

    uuid = UUID.uuid3WithNamespace("this is my string", .nil);
    out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "A0E362D3-1BAE-3DA4-BFF2-AD6AE4F44DBF");

    try std.testing.expect(uuid.version() == 3);
}

test "generates new UUID5s based on different pre defined namespace" {
    var buf36: [36]u8 = undefined;
    var uuid = UUID.uuid5WithNamespace("this is my string", .dns);
    var out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "618CA8EC-BE67-58C8-91CB-03898F031C15");

    uuid = UUID.uuid5WithNamespace("this is my string", .url);
    out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "5F7F8A62-9C6E-559A-AF1D-259956DD3F82");

    uuid = UUID.uuid5WithNamespace("this is my string", .oid);
    out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "C326C1BF-7F09-514F-AB04-FD8E7CEEFB8D");

    uuid = UUID.uuid5WithNamespace("this is my string", .x500);
    out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "E8BA8088-BA8B-513F-9421-2BC756E682F6");

    uuid = UUID.uuid5WithNamespace("this is my string", .nil);
    out = uuid.formatUUID(.default, &buf36);
    try std.testing.expectEqualStrings(out, "C0A235AC-BD72-571B-84BF-85B22856BC00");

    try std.testing.expect(uuid.version() == 5);
}
